# Generated by Django 4.2.5 on 2023-09-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address_with_money',
            fields=[
                ('address', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='All_Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='idk',
            fields=[
                ('address', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
                ('start_height', models.PositiveIntegerField()),
                ('end_height', models.PositiveIntegerField()),
                ('crypto', models.CharField(max_length=16)),
                ('ms', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='p2pkh',
            fields=[
                ('address', models.CharField(max_length=34, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='p2sh',
            fields=[
                ('address', models.CharField(max_length=34, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='p2wpkh',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='p2wsh',
            fields=[
                ('address', models.CharField(max_length=62, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Win_Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=512)),
                ('account', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=8)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=128)),
                ('totalbalance', models.DecimalField(decimal_places=8, max_digits=128)),
            ],
        ),
    ]
