# Generated by Django 4.2.5 on 2023-09-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wif',
            new_name='address',
        ),
    ]
