# Generated by Django 4.2.5 on 2023-09-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_checked_mnemonic',
            fields=[
                ('mnemonic', models.CharField(max_length=512, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='All_Wallet',
        ),
    ]
