# Generated by Django 4.2.5 on 2023-09-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_all_wallet_win_wallet_delete_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='win_wallet',
            name='totalbalance',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=128),
            preserve_default=False,
        ),
    ]
