# Generated by Django 4.2.5 on 2023-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_p2pkh_p2sh_p2wpkh_p2wsh'),
    ]

    operations = [
        migrations.CreateModel(
            name='idk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='p2pkh',
            name='address',
            field=models.CharField(max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='p2sh',
            name='address',
            field=models.CharField(max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='p2wpkh',
            name='address',
            field=models.CharField(max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name='p2wsh',
            name='address',
            field=models.CharField(max_length=62, unique=True),
        ),
    ]
