# Generated by Django 4.2.5 on 2023-09-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_idk_alter_p2pkh_address_alter_p2sh_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
            ],
        ),
    ]
