# Generated by Django 4.2.5 on 2023-09-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='last',
            name='crypto',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
