# Generated by Django 4.2.5 on 2023-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_last_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='last',
            name='ms',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='last',
            name='start_height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
