# Generated by Django 4.2.5 on 2023-09-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_last_ms_last_start_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='last',
            name='end_height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
