# Generated by Django 4.2.5 on 2023-09-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_last_end_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idk',
            name='id',
        ),
        migrations.RemoveField(
            model_name='p2pkh',
            name='id',
        ),
        migrations.RemoveField(
            model_name='p2sh',
            name='id',
        ),
        migrations.RemoveField(
            model_name='p2wpkh',
            name='id',
        ),
        migrations.RemoveField(
            model_name='p2wsh',
            name='id',
        ),
        migrations.AlterField(
            model_name='idk',
            name='address',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='p2pkh',
            name='address',
            field=models.CharField(max_length=34, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='p2sh',
            name='address',
            field=models.CharField(max_length=34, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='p2wpkh',
            name='address',
            field=models.CharField(max_length=42, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='p2wsh',
            name='address',
            field=models.CharField(max_length=62, primary_key=True, serialize=False, unique=True),
        ),
    ]
